export const products = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    category: "Electronics",
    price: 89.99,
    originalPrice: 149.99,
    commission: 12,
    rating: 4.8,
    reviews: 2341,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop",
    badge: "Best Seller",
    badgeColor: "purple",
  },
  {
    id: 2,
    name: "Smart Fitness Tracker Watch",
    category: "Wearables",
    price: 59.99,
    originalPrice: 99.99,
    commission: 15,
    rating: 4.6,
    reviews: 1876,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=300&fit=crop",
    badge: "Hot Deal",
    badgeColor: "cyan",
  },
  {
    id: 3,
    name: "Portable Bluetooth Speaker",
    category: "Electronics",
    price: 45.99,
    originalPrice: 79.99,
    commission: 10,
    rating: 4.7,
    reviews: 3102,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=300&fit=crop",
    badge: "Trending",
    badgeColor: "emerald",
  },
  {
    id: 4,
    name: "Ergonomic Office Chair",
    category: "Furniture",
    price: 299.99,
    originalPrice: 499.99,
    commission: 18,
    rating: 4.9,
    reviews: 987,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop",
    badge: "Top Rated",
    badgeColor: "purple",
  },
  {
    id: 5,
    name: "LED Ring Light Kit",
    category: "Photography",
    price: 34.99,
    originalPrice: 59.99,
    commission: 20,
    rating: 4.5,
    reviews: 4521,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=300&fit=crop",
    badge: "New",
    badgeColor: "cyan",
  },
  {
    id: 6,
    name: "Mechanical Gaming Keyboard",
    category: "Gaming",
    price: 79.99,
    originalPrice: 129.99,
    commission: 14,
    rating: 4.8,
    reviews: 2198,
    image: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&h=300&fit=crop",
    badge: "Popular",
    badgeColor: "emerald",
  },
];

export const earningsData = [
  { month: "Jan", earnings: 1200, clicks: 3400, conversions: 45 },
  { month: "Feb", earnings: 1900, clicks: 4200, conversions: 62 },
  { month: "Mar", earnings: 1600, clicks: 3800, conversions: 54 },
  { month: "Apr", earnings: 2400, clicks: 5100, conversions: 78 },
  { month: "May", earnings: 2100, clicks: 4700, conversions: 71 },
  { month: "Jun", earnings: 3200, clicks: 6300, conversions: 98 },
  { month: "Jul", earnings: 2800, clicks: 5800, conversions: 89 },
];

export const recentActivity = [
  { id: 1, type: "sale", product: "Wireless Headphones", amount: 10.80, time: "2 min ago", user: "john_d***" },
  { id: 2, type: "click", product: "Smart Watch", amount: 0, time: "5 min ago", user: "sarah_m***" },
  { id: 3, type: "sale", product: "Bluetooth Speaker", amount: 4.60, time: "12 min ago", user: "mike_r***" },
  { id: 4, type: "sale", product: "Office Chair", amount: 53.99, time: "28 min ago", user: "emma_k***" },
  { id: 5, type: "click", product: "Ring Light Kit", amount: 0, time: "45 min ago", user: "alex_t***" },
  { id: 6, type: "sale", product: "Gaming Keyboard", amount: 11.20, time: "1 hr ago", user: "chris_w***" },
];

export const testimonials = [
  {
    name: "Sarah Mitchell",
    role: "Full-time Affiliate Marketer",
    avatar: "SM",
    content: "AffiliateHub transformed my side hustle into a $8k/month income stream. The product catalog and real-time analytics are game changers.",
    earnings: "$8,400/mo",
    color: "purple",
  },
  {
    name: "James Rodriguez",
    role: "Dropshipping Entrepreneur",
    avatar: "JR",
    content: "The commission rates here are unmatched. I've tried 6 other platforms and nothing comes close to the product variety and payout speed.",
    earnings: "$12,200/mo",
    color: "cyan",
  },
  {
    name: "Priya Sharma",
    role: "Content Creator & Affiliate",
    avatar: "PS",
    content: "Setup took 10 minutes. Within my first week I had 3 sales. The dashboard makes it so easy to track everything in one place.",
    earnings: "$3,800/mo",
    color: "emerald",
  },
];

export const features = [
  {
    icon: "TrendingUp",
    title: "Real-Time Analytics",
    description: "Track clicks, conversions, and earnings live. Know exactly what's working and scale it fast.",
    color: "purple",
  },
  {
    icon: "Package",
    title: "10,000+ Products",
    description: "Curated dropshipping catalog across 50+ categories. High-margin, fast-shipping products ready to promote.",
    color: "cyan",
  },
  {
    icon: "DollarSign",
    title: "Up to 25% Commission",
    description: "Industry-leading commission rates with weekly payouts. No minimum threshold to withdraw.",
    color: "emerald",
  },
  {
    icon: "Link",
    title: "Smart Link Builder",
    description: "Generate trackable affiliate links in seconds. Deep linking, custom slugs, and QR codes included.",
    color: "purple",
  },
  {
    icon: "Shield",
    title: "Fraud Protection",
    description: "AI-powered fraud detection keeps your account safe and ensures every commission is legitimate.",
    color: "cyan",
  },
  {
    icon: "Zap",
    title: "Instant Setup",
    description: "Go from signup to your first affiliate link in under 5 minutes. No approval waiting period.",
    color: "emerald",
  },
];
